version: "3"

services:


  v2ray:
    image: v2fly/v2fly-core:v4.27.4
    restart: always
    volumes:
      - ./v2ray:/etc/v2ray
      - ./log/v2ray:/var/log/v2ray
    ports:
      - 8300:8300
    command: ["v2ray", "-config=/etc/v2ray/config.json"]


  v2ray-mu:
    image: jinaviva/v2ray-mu:dev
    restart: always
    volumes:
      - ./log/v2ray-mu:/var/log/v2ray-mu
    logging:
      driver: json-file
      options:
         max-size: "200k"
         max-file: "10"
    env_file:
      - mu.env
 

